### PR TITLE
🚀 replace old logo Zenika by the new one

### PR DESCRIPTION
**Pull request by jeanphibaconnais**

### CODE REVIEW

**Comment by arthurzenika** [comment]
* Some of the SVGs seem to change size, is that expected ? 
* Some of the SVGs seem to not visually change at all, any reason for that ?

**Comment by jeanphibaconnais** [comment]
- no, I think it's a mistake 😕 I mix icons and shapes repertory 
- no, but as we use a 'npm run generate', I think this change any svg 🤷‍♂️

**Comment by jeanphibaconnais** [comment]
@arthurzenika I resize some icons 😅

**Comment by arthurzenika** [comment]
@jeanphibaconnais great. packages/assets/src/icons/body-tatoo-1.svg seems to be still wrong, but the rest look great. Almost there !

**Comment by jeanphibaconnais** [comment]
Rha 😅  I just fixed it. I ask to @hgwood if the error during deploy preview speak him about

**Review by arthurzenika — APPROVED** [review]

**Pull request merged**
